### PR TITLE
Support master_lb_enabled attribute for cluster resource

### PR DESCRIPTION
**Pull request by iokiwi**

### CODE REVIEW

**Comment by iokiwi** [comment]
Failing until related merge request in gophercloud has been merged https://github.com/gophercloud/gophercloud/pull/2102

**Comment by iokiwi** [comment]
Recheck

**Comment by ozerovandrei** [comment]
The needed field is also missing in [Cluster](https://github.com/gophercloud/gophercloud/blob/master/openstack/containerinfra/v1/clusters/results.go#L84) result struct.

**Comment by kayrus** [comment]
Close in favor of #1767

**Pull request closed without merging**
