### PR TITLE
Bump Gophercloud

### PR DESCRIPTION
**Pull request by pierreprinetti**
Upgrade Gophercloud to [v0.23.0][1] and its `utils` library to the
latest version available.

This patch is supposed to pick up all the bugfixes introduced in the library since v0.17.1.

[1]: https://github.com/gophercloud/gophercloud/releases/tag/v0.23.0

### CODE REVIEW

**Comment by pierreprinetti** [comment]
recheck

**Comment by pierreprinetti** [comment]
recheck

**Comment by EmilienM** [comment]
No need to recheck, Manila shares failed to be created:

```
2021-11-22 12:59:42.714 | + /opt/stack/new/manila/devstack/plugin.sh:create_default_share_type:1 :   exit_trap
```

https://logs.openlabtesting.org/logs/15/1315/5d3f417e831a14bea1555a665b4d3c978069c0aa/check/terraform-provider-openstack-acceptance-test-foo/cdc8eeb/logs/devstacklog.txt

Someone will have to fix this.

**Comment by EmilienM** [comment]
Likely broken by https://review.opendev.org/c/openstack/devstack/+/780417

**Comment by EmilienM** [comment]
recheck

**Comment by EmilienM** [comment]
Now failing on Neutron trunks tests:
https://logs.openlabtesting.org/logs/15/1315/5d3f417e831a14bea1555a665b4d3c978069c0aa/check/terraform-provider-openstack-acceptance-test-foo/d840c80/test_results.html

But at least Manila issue seems solved now.

**Review by ozerovandrei — APPROVED** [review]
LGTM thank you @pierreprinetti 

Trunk tests will be disabled https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1323

**Pull request merged**
