### PR TITLE
Enable errcheck linter

### PR DESCRIPTION
**Pull request by dkder3k**
For #1063

### CODE REVIEW

**Comment by dkder3k** [comment]
recheck

**Comment by dkder3k** [comment]
```
10:35:38 [DEBUG] Attempting to update share 
10:35:38 [DEBUG] Waiting for state to become: [success] 
10:35:38 [DEBUG] OpenStack Request URL: PUT http://192.168.0.7/share/v2/shares/7585115e-3c25-4f67-b802-6df3661276ac 
10:35:38 [DEBUG] OpenStack Request Headers: Accept: application/json Cache-Control: no-cache Content-Type: application/json Openstack-Api-Version: sharev2 2.14 User-Agent: HashiCorp Terraform/0.12.7-sdk (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 gophercloud/2.0.0 X-Auth-Token: *** X-Openstack-Manila-Api-Version: 2.14 
10:35:38 [DEBUG] OpenStack Request Body: { "share": { "display_description": "", "display_name": "nfs_share_updated", "is_public": true } } 
10:35:38 [DEBUG] OpenStack Response Code: 403 
10:35:38 [DEBUG] OpenStack Response Headers: Content-Length: 108 Content-Type: application/json Date: Fri, 12 Mar 2021 10:35:38 GMT Server: Apache/2.4.29 (Ubuntu) Vary: X-OpenStack-Manila-API-Version X-Compute-Request-Id: req-c4e57f79-56e3-4ce7-a288-db02237df63f X-Openstack-Manila-Api-Version: 2.14 
10:35:38 [DEBUG] OpenStack Response Body: { "forbidden": { "code": 403, "message": "User is not authorized to set 'is_public' to True in the request." } } 
10:35:38 [DEBUG] openstack_sharedfilesystem_share_v2.share_1: apply errored, but we're indicating that via the Error pointer rather than returning it: Error updating 7585115e-3c25-4f67-b802-6df3661276ac share: forbidden (403): User is not authorized to set 'is_public' to True in the request. 
10:35:38 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error updating 7585115e-3c25-4f67-b802-6df3661276ac share: forbidden (403): User is not authorized to set 'is_public' to True in the request. 
10:35:38 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error updating 7585115e-3c25-4f67-b802-6df3661276ac share: forbidden (403): User is not authorized to set 'is_public' to True in the request. 
10:35:38 [DEBUG] New state was assigned lineage "5ed621e7-d467-d966-4170-5b5a95ad40d9" TestAccSFSV2Share_basic: testing.go:705: Step 1 error: errors during apply: Error: Error updating 7585115e-3c25-4f67-b802-6df3661276ac share: forbidden (403): User is not authorized to set 'is_public' to True in the request. on /tmp/tf-test176343904/main.tf line 2: (source code not available)
```
Looks like [this test-case](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_sharedfilesystem_share_v2_test.go#L31) is broken because of permissions. Were there any changes recently in test environment?

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Comment by ozerovandrei** [comment]
I don't know why that test is failing. I created an issue to investigate it: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1205

**Pull request merged**
