### PR TITLE
Enable govet and maligned linters

### PR DESCRIPTION
**Pull request by dkder3k**
For #1063

### CODE REVIEW

**Comment by dkder3k** [comment]
Recheck

**Comment by dkder3k** [comment]
Recheck

**Review by kayrus — APPROVED** [review]
LGTM, thanks

**Comment by dkder3k** [comment]
Look like `TestAccNetworkingV2FloatingIP_subnetIDs` failed. I've found some related logs, will check tomorrow

```
 19:50:54 [DEBUG] openstack_networking_floatingip_v2 create options: openstack.FloatingIPCreateOpts{CreateOpts:(*floatingips.CreateOpts)(0xc004132000), ValueSpecs:map[string]string{}} 
 19:50:54 [DEBUG] openstack_networking_floatingip_v2 create options (try 1): openstack.FloatingIPCreateOpts{CreateOpts:(*floatingips.CreateOpts)(0xc004132000), ValueSpecs:map[string]string{}} 
 19:50:54 [DEBUG] OpenStack Request URL: POST http://192.168.0.27:9696/v2.0/floatingips 
 19:50:54 [DEBUG] OpenStack Request Headers: Accept: application/json Cache-Control: no-cache Content-Type: application/json User-Agent: HashiCorp Terraform/0.12.7-sdk (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 gophercloud/2.
0.0 X-Auth-Token: *** 
 19:50:54 [DEBUG] OpenStack Request Body: { "floatingip": { "description": "test", "floating_network_id": "1dc36eee-4510-440f-95c1-2bb47e6ba6ae", "subnet_id": "1dc36eee-4510-440f-95c1-2bb47e6ba6ae" } } 
 19:50:56 [DEBUG] OpenStack Response Code: 404 
 19:50:56 [DEBUG] OpenStack Response Headers: Content-Length: 136 Content-Type: application/json Date: Mon, 08 Feb 2021 19:50:56 GMT X-Openstack-Request-Id: req-911e4245-8e31-4129-af3a-18c4511a92b5 
 19:50:56 [DEBUG] OpenStack Response Body: { "NeutronError": { "detail": "", "message": "Subnet 1dc36eee-4510-440f-95c1-2bb47e6ba6ae could not be found.", "type": "SubnetNotFound" } } 
 19:50:56 [DEBUG] openstack_networking_floatingip_v2 create options (try 2): openstack.FloatingIPCreateOpts{CreateOpts:(*floatingips.CreateOpts)(0xc004132000), ValueSpecs:map[string]string{}} 
 19:50:56 [DEBUG] OpenStack Request URL: POST http://192.168.0.27:9696/v2.0/floatingips 
 19:50:56 [DEBUG] OpenStack Request Headers: Accept: application/json Cache-Control: no-cache Content-Type: application/json User-Agent: HashiCorp Terraform/0.12.7-sdk (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 gophercloud/2.
0.0 X-Auth-Token: *** 
 19:50:56 [DEBUG] OpenStack Request Body: { "floatingip": { "description": "test", "floating_network_id": "1dc36eee-4510-440f-95c1-2bb47e6ba6ae", "subnet_id": "0cbce503-b28a-412e-8b67-e60e7cbc99d2" } } 
 19:50:59 [DEBUG] OpenStack Response Code: 400 
 19:50:59 [DEBUG] OpenStack Response Headers: Content-Length: 172 Content-Type: application/json Date: Mon, 08 Feb 2021 19:50:59 GMT X-Openstack-Request-Id: req-7ca594e8-3470-438c-88a3-e53a5048ff0f 
 19:50:59 [DEBUG] OpenStack Response Body: { "NeutronError": { "detail": "", "message": "Unable to find any IP address on external network 1dc36eee-4510-440f-95c1-2bb47e6ba6ae.", "type": "ExternalIpAddressExhausted" } } 
 19:50:59 [DEBUG] openstack_networking_floatingip_v2.fip_1: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating openstack_networking_floatingip_v2: Bad request with: [POST http://192.168
.0.27:9696/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalIpAddressExhausted", "message": "Unable to find any IP address on external network 1dc36eee-4510-440f-95c1-2bb47e6ba6ae.", "detail": ""}} 
 19:50:59 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating openstack_networking_floatingip_v2: Bad request with: [POST http://192.168.0.27:9696/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalIpAddr
essExhausted", "message": "Unable to find any IP address on external network 1dc36eee-4510-440f-95c1-2bb47e6ba6ae.", "detail": ""}} 
 19:50:59 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating openstack_networking_floatingip_v2: Bad request with: [POST http://192.168.0.27:9696/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalIpAddre
ssExhausted", "message": "Unable to find any IP address on external network 1dc36eee-4510-440f-95c1-2bb47e6ba6ae.", "detail": ""}} 
 19:50:59 [DEBUG] New state was assigned lineage "ad6830b0-95af-7bc8-495b-5f1b62019156" TestAccNetworkingV2FloatingIP_subnetIDs: testing.go:705: Step 0 error: errors during apply: Error: Error creating openstack_networking_floatingip_v2: 
Bad request with: [POST http://192.168.0.27:9696/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalIpAddressExhausted", "message": "Unable to find any IP address on external network 1dc36eee-4510-440f-95c1-2bb47e6ba6ae.
", "detail": ""}} on /tmp/tf-test680417696/main.tf line 6: (source code not available)
```

**Comment by kayrus** [comment]
@dkder3k the same test passed in #1163. can you rebase on main branch?

**Pull request merged**
