### PR TITLE
VPNaaS endpoint group resource: use schema.TypeSet for endpoints (V2)

### PR DESCRIPTION
**Pull request by oseiberts11**
Hi! I'm trying to improve on merge request !1089.

After some to-and-fro to get the tests running locally (I don't mess with a devstack, I have a real cloud at hand; but my test user wasn't called `demo` of course), it seems that what I think is the relevant test `TestAccGroupV2_basic` passes.

I triggered a recheck of !1089 because the logs seem to have expired, but when I looked, that specific test seems to be skipped.
```
2021-05-14 15:09:42.193729 | ubuntu-bionic | === RUN   TestAccGroupV2_basic
2021-05-14 15:09:42.193739 | ubuntu-bionic |     TestAccGroupV2_basic: provider_test.go:163: This environment does not support VPN tests
2021-05-14 15:09:42.193749 | ubuntu-bionic | --- SKIP: TestAccGroupV2_basic (0.00s)
2021-05-14 15:09:42.193759 | ubuntu-bionic | === RUN   TestAccGroupV2_update
2021-05-14 15:09:42.193769 | ubuntu-bionic |     TestAccGroupV2_update: provider_test.go:163: This environment does not support VPN tests
```

So let's see what happens.

### CODE REVIEW

**Comment by oseiberts11** [comment]
I added a commit to reinstate a disabled test: `testAccCheckEndpoints()`. I'm of course not too familiar with the terraform code, so I just found out with trial and error what the values in Attributes are. So I found
```
[DEBUG] key: endpoints.1091970838 value: 10.3.0.0/24
[DEBUG] key: endpoints.# value: 2
[DEBUG] key: region value: zbk
[DEBUG] key: name value: Group 1
[DEBUG] key: tenant_id value: 4d421666b0054dcaabb6e35a7daada46
[DEBUG] key: endpoints.2377918344 value: 10.2.0.0/24
[DEBUG] key: description value:
[DEBUG] key: type value: cidr
[DEBUG] key: id value: 605e38bb-cf3d-4a73-90f3-d8538b0b77d4
```
I didn't quickly find some easy way to access the various `endpoints.<number>` keys. The numbers seem random (maybe some hash?). I hope you can provide some guidance to improve this.

Similarly I looked at the disabled test `testAccCheckLifetime()` and there I see
```
[DEBUG] key: pfs value: group14
[DEBUG] key: encryption_algorithm value: aes-128
[DEBUG] key: name value:
[DEBUG] key: description value:
[DEBUG] key: lifetime.# value: 1
[DEBUG] key: lifetime.452086442.value value: 1200
[DEBUG] key: lifetime.452086442.units value: seconds
[DEBUG] key: auth_algorithm value: sha256
[DEBUG] key: tenant_id value: 4d421666b0054dcaabb6e35a7daada46
[DEBUG] key: transform_protocol value: esp
[DEBUG] key: region value: zbk
[DEBUG] key: id value: 8f79b793-77fe-4ed7-8655-0301835806bb
[DEBUG] key: encapsulation_mode value: tunnel
[DEBUG] key: encapsulation_mode value: tunnel
[DEBUG] key: pfs value: group14
[DEBUG] key: name value:
[DEBUG] key: tenant_id value: 4d421666b0054dcaabb6e35a7daada46
[DEBUG] key: transform_protocol value: esp
[DEBUG] key: lifetime.1066997110.value value: 1400
[DEBUG] key: lifetime.1066997110.units value: seconds
[DEBUG] key: region value: zbk
[DEBUG] key: encryption_algorithm value: aes-128
[DEBUG] key: id value: 8f79b793-77fe-4ed7-8655-0301835806bb
[DEBUG] key: description value:
[DEBUG] key: auth_algorithm value: sha256
[DEBUG] key: lifetime.# value: 1
```
Here some help with accessing these `lifetime.<number>.anotherkey` keys would be even more helpful!

**Comment by oseiberts11** [comment]
The duplicate keys `lifetime.#` are really "interesting" in the last case....

**Comment by oseiberts11** [comment]
ping!

**Review by ozerovandrei — APPROVED** [review]
LGTM
@oseiberts11 let me know if it's ready to be merged

**Comment by oseiberts11** [comment]
@ozerovandrei from my point of view it is.

**Pull request merged**
