### PR TITLE
Fix update of node_count field for containerinfra_cluster_v1 resource and {min,max}_node_count fields for containerinfra_nodegroup_v1 resource

### LINKED ISSUE #1102: Two obvious bugs about openstack_containerinfra
Hi there,
1. `floating_ip_enabled=true` is not take effect in openstack_containerinfra_clustertemplate_v1
2. I modify `node_count`, then apply ,it should be modify the node number of cluster, but it return error:  
```
Error: Error updating openstack_containerinfra_cluster_v1 c6350dd3-91c4-4106-a9ab-09d15635692d: Bad request with: [PATCH http://x.x.x.x:9511/v1/clusters/c6350dd3-91c4-4106-a9ab-09d15635692d], error message: {"errors": [{"request_id": "", "code": "client", "status": 400, "title": "Invalid input for field/attribute node_count", "detail": "Invalid input for field/attribute node_count. Value: '4'. '<' not supported between instances of 'str' and 'int'", "links": []}]}

  on os.tf line 41, in resource "openstack_containerinfra_cluster_v1" "cluster_1":
  41: resource "openstack_containerinfra_cluster_v1" "cluster_1" {

``` 

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/openstack v1.33.0

### Affected Resource(s)
openstack_containerinfra_cluster_v1
openstack_containerinfra_clustertemplate_v1

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name   = var.user_name
  tenant_name = var.tenant_name
  password    = var.password
  auth_url    = var.auth_url
  region      = var.region
}

resource "openstack_containerinfra_clustertemplate_v1" "clustertemplate_1" {
  name                  = var.clustertemplate_name
  image                 = var.image
  coe                   = "kubernetes"
  flavor                = var.flavor
  master_flavor         = var.master_flavor
  dns_nameserver        = "x.x.x.x"
  docker_storage_driver = "overlay2"
  docker_volume_size    = 40
  network_driver        = var.network_driver
  server_type           = "vm"
  master_lb_enabled     = var.master_lb_enabled
  floating_ip_enabled   = var.floating_ip_enabled
  external_network_id   = var.external_network_id
  fixed_network = var.fixed_network
  fixed_subnet = var.fixed_subnet

  labels = {
    kube_tag                         = var.kube_tag
    kube_dashboard_enabled           = "true"
    prometheus_monitoring            = "true"
    influx_grafana_dashboard_enabled = "true"
    container_infra_prefix           = "xxxxxx"
  }
}

resource "openstack_containerinfra_cluster_v1" "cluster_1" {
  name                = var.cluster_name
  cluster_template_id = openstack_containerinfra_clustertemplate_v1.clustertemplate_1.id
  master_count        = var.master_count
  node_count          = var.node_count
  keypair             = "mykey"
  floating_ip_enabled   = var.floating_ip_enabled
  timeouts {
    create = var.timeout
    delete = var.timeout
  }
}

variable "floating_ip_enabled"{
  type = bool
  default = true
}

variable "node_count" {
  type = number
  default = 4
}

```

### PR DESCRIPTION
**Pull request by pawcykca**
Close #1102 

This PR should allow users to update node_count of cluster resource.

### CODE REVIEW

**Comment by MrFreezeex** [comment]
I am guessing that if this is the right fix, it would also applies to {min,max}_node_count on the nodegroup resource as well.

**Comment by pawcykca** [comment]
> Hmm on our OpenStack cluster changing the number of nodes was working fine (IIRC our magnum is running train version). Maybe magnum changed something in the API...

I'm testing this feature on Openstack Ussuri.

Based on official API reference, samples and source code (for both Train and Ussuri releases) the value of `node_count` parameter should be `int`, not `string`:
https://github.com/openstack/magnum/blob/stable/ussuri/api-ref/source/clusters.inc#update-information-of-cluster
https://github.com/openstack/magnum/blob/stable/ussuri/magnum/api/controllers/v1/cluster.py#L106

**Comment by pawcykca** [comment]
> I am guessing that if this is the right fix, it would also applies to {min,max}_node_count on the nodegroup resource as well.

That's true.
I have also fixed this resource.

**Review by nikParasyr — APPROVED** [review]

**Review by ozerovandrei — APPROVED** [review]
I also don't have a Magnum environment currently but LGTM

**Pull request merged**
