### PR TITLE
WIP: Add any option in networking secgroup rule

### PR DESCRIPTION
**Pull request by HappyFX**
Add option "Any" in security group rules, according the [documentaion](https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/security-group-rule.html#cmdoption-openstack-security-group-rule-create-protocol):

```bash
Network version 2:
IP protocol (ah, dccp, egp, esp, gre, icmp, igmp, ipv6-encap, ipv6-frag, ipv6-icmp, ipv6-nonxt, ipv6-opts, ipv6-route, ospf, pgm, rsvp, sctp, tcp, udp, udplite, vrrp and integer representations [0-255] or any; default: any (all protocols))
```

Need 2 update [gophercloud](https://github.com/gophercloud/gophercloud/pull/2310) be4 test will pass

### CODE REVIEW

**Comment by HappyFX** [comment]
@ozerovandrei how to run test once more?

**Comment by ozerovandrei** [comment]
@HappyFX Hello.
Could you please rebase, CI stuff was changed.

**Comment by mikejoh** [comment]
@ozerovandrei :wave: looks like @HappyFX did a rebase and then nothing happened, it would be awesome if we could get this in! Let me know if i can help out, there were a bunch of acceptance tests that failed? The fix referenced in this PR in `gophercloud` went out with `v0.25.0` last year and this project is at `v1.2.1` of `gophercloud`, should be alright to merge after rebase and given that tests passes etc.

**Comment by kayrus** [comment]
@HappyFX  need to rebase on master to trigger new tests
otherwise feel free to submit a new PR yourself.

**Comment by mikejoh** [comment]
> @HappyFX need to rebase on master to trigger new tests otherwise feel free to submit a new PR yourself.

:heavy_check_mark: i'll hold a bit and see if author might get back to this!

Thanks!

**Comment by kayrus** [comment]
I've managed to rebase this PR. I think it does make sense to move the protocol verification logic directly into the schema's `ValidateFunc: validation.StringInSlice(...)`. This will catch the wrong protocol on early stage.

**Comment by mikejoh** [comment]
> I've managed to rebase this PR. I think it does make sense to move the protocol verification logic directly into the schema's `ValidateFunc: validation.StringInSlice(...)`. This will catch the wrong protocol on early stage.

:+1: Yes, that makes sense. It would be another place to update once another protocol is added, but failing fast is also good, i guess it depends. And `gophercloud` isn't exposing anything that could be reused here either AFAICT?

<details><summary>Something like this?</summary>
<p>

```golang
	"protocol": {
		Type:     schema.TypeString,
		Optional: true,
		ForceNew: true,
		Computed: true,
		ValidateFunc: validation.StringInSlice([]string{
			"ah",
			"dccp",
			"egp",
			"esp",
			"gre",
			"hopopt",
			"icmp",
			"igmp",
			"ip",
			"ipip",
			"ipv6-encap",
			"ipv6-frag",
			"ipv6-icmp",
			"icmpv6",
			"ipv6-nonxt",
			"ipv6-opts",
			"ipv6-route",
			"ospf",
			"pgm",
			"rsvp",
			"sctp",
			"tcp",
			"udp",
			"udplite",
			"vrrp",
			"any",
		}, false),
	},
```

</p>
</details>

The complete list was taken from [Neutron API ref](https://docs.openstack.org/api-ref/network/v2/?expanded=create-security-group-rule-detail#create-security-group-rule) and added the `any` option which the current PR adds. I created this PR https://github.com/gophercloud/gophercloud/pull/2583 to add the ones missing. Would require another PR in here once it get merged!

**Comment by HappyFX** [comment]
The main problem, that in openstack API normalization of strig `any` is `None` in object JSON, not a string. 
All `any` is alias in openstack sdk for `None`. In gopher cloud I have issue with this:
https://github.com/gophercloud/gophercloud/issues/2442
I can't figure out in go lang add null value in dict of strings.
https://github.com/gophercloud/gophercloud/blob/9d06eaee3e740092a8da78369eb8554ca6d01aae/openstack/networking/v2/extensions/security/rules/requests.go#L80
It must be `ProtocolAny       RuleProtocol  = null`

**Comment by mikejoh** [comment]
> The main problem, that in openstack API normalization of strig `any` is `None` in object JSON, not a string. All `any` is alias in openstack sdk for `None`. In gopher cloud I have issue with this: [gophercloud/gophercloud#2442](https://github.com/gophercloud/gophercloud/issues/2442) I can't figure out in go lang add null value in dict of strings. https://github.com/gophercloud/gophercloud/blob/9d06eaee3e740092a8da78369eb8554ca6d01aae/openstack/networking/v2/extensions/security/rules/requests.go#L80 It must be `ProtocolAny RuleProtocol = nil`
> 
> [HappyFX/gophercloud@b09c837](https://github.com/HappyFX/gophercloud/commit/b09c83712f42cee7a6085c52e7146e7228c2b222)

Right, thanks for the explanation @HappyFX! Not very straight forward to support `any` then..

**Pull request closed without merging**
