### PR TITLE
Add networking_portforwarding_v2 resource

### PR DESCRIPTION
**Pull request by simonre**
This PR adds a resource to add port forwardings for floating IPs

### CODE REVIEW

**Comment by ozerovandrei** [comment]
@simonre Hello.
Please vendor "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/portforwarding" by running:
```
go mod tidy
go mod vendor
```

We use Go modules with vendoring mode to manage dependencies: https://www.terraform.io/docs/providers/openstack/index.html#vendoring

**Comment by ozerovandrei** [comment]
I've performed some refactoring and cleanup.
But there are some more tasks that should be done:
1. We should support `description` argument. But there is no support for it in the Gophercloud yet. So it should be updated and vendored.
2. There should be an acceptance test for `resourceNetworkPortForwardingV2Update` logic.
3. Importer and acceptance test for it should be implemented if it's possible.

**Comment by simonre** [comment]
Hi @ozerovandrei ,
I would love to finish this but unfortunately I have changed jobs and no longer have time and the resources to work on this. I hope somebody else can take over.

**Comment by ozerovandrei** [comment]
@simonre no worries, I'll finish this.

**Comment by frittentheke** [comment]
@simonre thank you very much for implementing this feature!
Do you see any chance to finish the PR / get it ready to merge?

I gladly offer my help if you require an assistance or would even take over the PR if you cannot the spare the time anymore.

**Comment by frittentheke** [comment]
@simonre thank you very much for implementing this feature!

@ozerovandrei 
Do you see any chance to finish the PR / get it ready to merge?
I gladly offer my help if you require any assistance or would even take over the PR if you cannot the spare the time.

**Comment by ozerovandrei** [comment]
@frittentheke Hello.
The reason why it has not been merged is because we don't have this feature enabled in OpenStack Neutron API server side in CI: https://github.com/theopenlab/openlab/issues/524

I can skip those tests running in CI If you can test this manually on your installation and confirm that those changes actually work.

**Comment by frittentheke** [comment]
> @frittentheke Hello.
> The reason why it has not been merged is because we don't have this feature enabled in OpenStack Neutron API server side in the CI: https://github.com/theopenlab/openlab/issues/524
> 
> I can skip those tests running in CI If you can test this manually on your installation and confirm that those changes actually work. 



I would gladly test the new code @ozerovandrei . Just let me know when and what to test exactly.

**Comment by rissson** [comment]
Any news on this?

**Comment by hvhaugwitz** [comment]
I also long for this feature and would be glad to test it on my installations.

**Comment by ozerovandrei** [comment]
@hvhaugwitz Hello. 
It would be great if you could test it. I can then skip those tests in CI for now and then merge this feature.

**Comment by frittentheke** [comment]
@ozerovandrei sorry for the massive delay. I now built this PR and tested it against a OpenStack Train cloud.
Creating, deleting and updating of forwardings works just fine. Also mapping between different internal and external ports, as well as targeting a different internal ports / IPs.

Let me know if this is sufficient for you to merge this, or if I shall test anything else.

**Comment by hvhaugwitz** [comment]
@ozerovandrei I successfully tested the `networking_portforwarding_v2` resource on an OpenStack Train installation. Adding, removing and changing port forwarding for multiple ports to different instances works as expected.

**Comment by ozerovandrei** [comment]
I disabled portforwarding tests until environment is ready.
Latest test run failed because of `TestAccSFSV2Share_basic Error: Error updating 4688c828-7864-450e-ba8f-0553290c80e5 share: forbidden (403): User is not authorized to set 'is_public' to True in the request.` which is unrelated to changes introduced in this PR.

Thank you for participating in development and testing of this feature!

**Pull request merged**
