### PR TITLE
openstack_images_image_v2: Make it possible to update image settings after resource creation

### PR DESCRIPTION
**Pull request by fitbeard**
This change makes usable feature introduced earlier in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1299
Tests were untouched because no new functionality was added.

### CODE REVIEW

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
@ozerovandrei Can you view it? Regardless of the failing tests I think everything is very simple and clear here.

**Comment by fitbeard** [comment]
recheck

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
