### PR TITLE
Update containerinfra tests

### PR DESCRIPTION
**Pull request by pawcykca**
Few updates for containerinfra tests.

Test 'TestAccContainerInfraV1ClusterTemplate_basic' need fix from PR #1455

### CODE REVIEW

**Comment by nikParasyr** [comment]
@pawcykca thanks for the PR. Are you running the tests locally? Cause unfortunately I haven’t been able to make magnum ci work ( see #1406 )

**Comment by pawcykca** [comment]
Yes, I'm running the test locally (Openstack Ussuri) and I'm also still working on few next updates (commits) to this PR.

**Comment by nikParasyr** [comment]
@pawcykca #1455 has been merged. let me know when this is ready as well. ty

**Comment by pawcykca** [comment]
@nikParasyr all containerinfra tests are ready.

**Review by nikParasyr — APPROVED** [review]
Thanks for your work :)

**Pull request merged**
