### PR TITLE
Tenant attribute support for openstack_dns_zone_v2

### PR DESCRIPTION
**Pull request by pbasov**
* Replicates `--all-projects` and `--sudo-project-id` functionality
    from openstackclient
  * Users can set project_id and create designate dns zones in a
    different project
  * Resource import support with `<zone_uuid>:<project_id>`
  * `project_id` attribute support for data source
  * Support for getting a zone id from a unique zone name by listing all
    projects

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck designate

**Comment by pbasov** [comment]
Looking closely at the test setup in openlab, will come back with a fix.

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
@ozerovandrei am I doing something stupid, or openlab CI is busted again?

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
@pbasov last designate run failed on tests and not on devstack setup. It has some strange errors [/job-output.txt.gz](https://logs.openlabtesting.org/logs/87/1087/eedde15164bfd40fcd3af8fa9f4fa4e3b69f900f/recheck-designate/terraform-provider-openstack-acceptance-test-designate/5b797bb/job-output.txt.gz):


```
Request forbidden: [GET http://192.168.0.18/dns/v2/zones/120130d1-e631-4a8e-b2c9-1b8fce186e6c]
```

You can type `recheck designate` in the https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1067 PR to see if those errors are related to your changes or not.

I'm not familiar with Designate API so I don't know if auth headers can cause that.

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
recheck designate

**Comment by pbasov** [comment]
@ozerovandrei @dkder3k TestAccOpenStackDNSZoneV2DataSource_basic was broken in #1083 by removing shared zoneName variable between zone creation and zone check steps. Introducing one more commit to fix.

**Comment by pbasov** [comment]
recheck designate

**Review by ozerovandrei — APPROVED** [review]
LGTM

Thank you for implementing this and fixing the bug @pbasov

**Pull request merged**
