### PR TITLE
Use `multierror` in `Read` operation in `r/compute_instance_v2`

### PR DESCRIPTION
**Pull request by lego963**
Minor changes in `r/compute_instance_v2`

### CODE REVIEW

**Comment by lego963** [comment]
I didn't run any acceptance tests. It would be great if someone help here. Thanks

**Comment by nikParasyr** [comment]
@lego963 Can you rebase and push again? not sure why ci wasnt triggered

**Comment by snebosh** [comment]
@nikParasyr hi, I'm a friend of lego963. github blocked his account for unknown reasons after creating a merge request here. He created a ticket in github support asking why it happened, but he has not been answered for more than a month.

**Comment by rgyrbu** [comment]
@nikParasyr hiho, I will create new PR. Can you close this one?

**Pull request closed without merging**
