### PR TITLE
Octavia: Add tags to loadbalancer

### PR DESCRIPTION
**Pull request by nikParasyr**
Add support for tags for openstack_lb_loadbalancer_v2
For #1300

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
@ozerovandrei I have 0 clue why the lbaas job is failing. It's not related to tests. I checked a bit devstack for possible updates that would affect us but couldnt find anything...

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
I can merge it if you sure it works and you tested it in some OpenStack installation.

**Comment by nikParasyr** [comment]
@ozerovandrei I run now the acceptance test that includes tags and it passed (Openstack Stein with octavia):
```
make testacc TEST=./openstack TESTARGS="-run=TestAccLBV2LoadBalancer_basic -count=1"                     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccLBV2LoadBalancer_basic -count=1 -timeout 120m
=== RUN   TestAccLBV2LoadBalancer_basic
--- PASS: TestAccLBV2LoadBalancer_basic (119.06s)
PASS
ok  	github.com/terraform-provider-openstack/terraform-provider-openstack/openstack	119.069s
```

I probably tested it as well before submitting, but it's over a month now so i cant recall 100%

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
