### PR TITLE
Update Terraform SDK to V2

### PR DESCRIPTION
**Pull request by ozerovandrei**
Use v2.7.1 version of terraform-plugin-sdk.

Cleanup imports.

Change `validation.SingleIP()` -> `validation.IsIPAddress`,
`validation.ValidateRFC3339TimeString` -> `validation.IsRFC3339Time`.

Replace `Removed` Schema property with `Deprecated`.

Provide context into CustomizeDiff functions.

Use functions with the new signatures to configure the Provider with
Terraform SDK V2.

Add context into resourceImagesImageV2UpdateComputedAttributes.

Fix gofmt in pathorcontents package.

Fix networking_port_v2 datasource issue: "profile: StateFunc is
extraneous, value should just be changed before setting on computed-only
field" by removing custom StateFunc.

Fix containerinfra_cluster_v1 resource issuze: "kubeconfig: TypeMap with
Elem *Resource not supported, use TypeList/TypeSet with Elem *Resource
or TypeMap with Elem *Schema" by changing type to Type.Schema and
updating flattenContainerInfraV1Kubeconfig function.

Change the deprecated "Providers" field of resource.Test to
"ProviderFactories".

Use CreateContext, ReadContext, UpdateContext, DeleteContext instead of
deprecated resource functions. Use diag.Diagnostics and Context for
those functions.

Disable `TestAccComputeV2SecGroup_self`,
`TestAccComputeV2SecGroup_lowerCaseCIDR`, `TestAccNetworkingV2Subnet_allocationPool`
tests since SDK V2 currently does not support indexes into TypeSet.

Disable `TestAccComputeV2FloatingIPAssociate_attachToFirstNetwork` test
since SDK V2 fails with collection error.

Add `image_name`, `power_state` attributes to `compute_instance_v2` datasource
since we try to set them just like in resource.

Convert blockstorage quotaset volume types map to map of strings before
calling Set.

Update `TestAccBlockStorageQuotasetV3_basic` volume types quotas.

Disabled flacky `TestAccNetworkingV2Trunk_trunkUpdateSubports` test since
it can fail with `PortInUse` error.

### CODE REVIEW

**Comment by nikParasyr** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
```
2021-08-04 01:33:03.350195 | TASK [fetch-zuul-cloner : Install zuul-cloner shim dependencies]
2021-08-04 01:33:04.775880 | ubuntu-focal | ERROR
2021-08-04 01:33:04.776159 | ubuntu-focal | {
2021-08-04 01:33:04.776199 | ubuntu-focal |   "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_pip_payload_HbJNZV/ansible_pip_payload.zip/ansible/modules/packaging/language/pip.py\", line 271, in <module>\nImportError: No module named pkg_resources\n",
2021-08-04 01:33:04.776227 | ubuntu-focal |   "msg": "Failed to import the required Python library (setuptools) on ubuntu's Python /usr/bin/python2. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
2021-08-04 01:33:04.776251 | ubuntu-focal | }
```

**Comment by ozerovandrei** [comment]
Related issue: https://github.com/theopenlab/openlab/issues/808

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
```
2021-08-21 17:05:25.971236 | ubuntu-focal | 2021/08/21 17:05:25 [WARN] could not locate a terraform executable on system path; continuing
2021-08-21 17:05:28.972058 | ubuntu-focal | cannot run Terraform provider tests: unexpected error: Get "https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=&version=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

```
2021-08-21 17:06:04.774667 | ubuntu-focal | Error: Error setting a member status to the "317cdc17-3763-4ed1-8317-51c3036a1a52" image share for the "6b42ca2487154dabb28bd49b31e5e257" member: Request forbidden: [PUT http://192.168.0.38/image/v2/images/317cdc17-3763-4ed1-8317-51c3036a1a52/members/6b42ca2487154dabb28bd49b31e5e257], error message: {"message": "Not allowed to update members for image 317cdc17-3763-4ed1-8317-51c3036a1a52.<br /><br />\n\n\n", "code": "403 Forbidden", "title": "Forbidden"}
2021-08-21 17:06:04.774804 | ubuntu-focal |
2021-08-21 17:06:04.775020 | ubuntu-focal |   with openstack_images_image_access_accept_v2.image_access_accept_1,
2021-08-21 17:06:04.775368 | ubuntu-focal |   on terraform_plugin_test.tf line 25, in resource "openstack_images_image_access_accept_v2" "image_access_accept_1":
2021-08-21 17:06:04.775684 | ubuntu-focal |   25: resource "openstack_images_image_access_accept_v2" "image_access_accept_1" {
2021-08-21 17:06:04.775738 | ubuntu-focal |
2021-08-21 17:06:04.776202 | ubuntu-focal |     TestAccImagesImageAccessAcceptV2_importBasic: import_openstack_images_image_access_accept_v2_test.go:12: Step 1/2 error: Error running apply: exit status 1
2021-08-21 17:06:04.776270 | ubuntu-focal |
2021-08-21 17:06:04.777551 | ubuntu-focal |         Error: Error setting a member status to the "317cdc17-3763-4ed1-8317-51c3036a1a52" image share for the "6b42ca2487154dabb28bd49b31e5e257" member: Request forbidden: [PUT http://192.168.0.38/image/v2/images/317cdc17-3763-4ed1-8317-51c3036a1a52/members/6b42ca2487154dabb28bd49b31e5e257], error message: {"message": "Not allowed to update members for image 317cdc17-3763-4ed1-8317-51c3036a1a52.<br /><br />\n\n\n", "code": "403 Forbidden", "title": "Forbidden"}
2021-08-21 17:06:04.777631 | ubuntu-focal |
2021-08-21 17:06:04.777917 | ubuntu-focal |           with openstack_images_image_access_accept_v2.image_access_accept_1,
2021-08-21 17:06:04.778281 | ubuntu-focal |           on terraform_plugin_test.tf line 25, in resource "openstack_images_image_access_accept_v2" "image_access_accept_1":
2021-08-21 17:06:04.778532 | ubuntu-focal |           25: resource "openstack_images_image_access_accept_v2" "image_access_accept_1" {
2021-08-21 17:06:04.778582 | ubuntu-focal |
```

```
2021-08-21 18:04:31.681398 | ubuntu-focal |     TestAccComputeV2SecGroup_self: resource_openstack_compute_secgroup_v2_test.go:95: Step 1/1 error: Check failed: Check 3/4 error: Error in test check: openstack_compute_secgroup_v2.sg_1: Attribute 'rule.3170486100.self' not found
2021-08-21 18:04:31.681651 | ubuntu-focal |         Test check address "rule.3170486100.self" likely indexes into TypeSet
2021-08-21 18:04:31.681830 | ubuntu-focal |         This is currently not possible in the SDK
2021-08-21 18:04:32.073913 | ubuntu-focal | 2021/08/21 18:04:32 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
```
```
2021-08-21 18:06:07.146269 | ubuntu-focal |     TestAccComputeV2SecGroup_lowerCaseCIDR: resource_openstack_compute_secgroup_v2_test.go:136: Step 1/1 error: Check failed: Check 2/2 error: Error in test check: openstack_compute_secgroup_v2.sg_1: Attribute 'rule.768649014.cidr' not found
2021-08-21 18:06:07.146499 | ubuntu-focal |         Test check address "rule.768649014.cidr" likely indexes into TypeSet
2021-08-21 18:06:07.146660 | ubuntu-focal |         This is currently not possible in the SDK
2021-08-21 18:06:07.544037 | ubuntu-focal | 2021/08/21 18:06:07 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
```
```
2021-08-21 18:12:51.307312 | ubuntu-focal | 2021/08/21 18:12:51 [DEBUG] OpenStack Response Body: {
2021-08-21 18:12:51.307505 | ubuntu-focal |   "code": "403 Forbidden",
2021-08-21 18:12:51.308092 | ubuntu-focal |   "message": "Not allowed to update members for image 1de8a905-939d-40c0-a5c5-65893016f5b2.\u003cbr /\u003e\u003cbr /\u003e\n\n\n",
2021-08-21 18:12:51.308271 | ubuntu-focal |   "title": "Forbidden"
2021-08-21 18:12:51.308360 | ubuntu-focal | }
2021-08-21 18:12:51.411571 | ubuntu-focal | 2021/08/21 18:12:51 [WARN] Got error running Terraform: exit status 1
2021-08-21 18:12:51.411671 | ubuntu-focal |
2021-08-21 18:12:51.412750 | ubuntu-focal | Error: Error setting a member status to the "1de8a905-939d-40c0-a5c5-65893016f5b2" image share for the "6b42ca2487154dabb28bd49b31e5e257" member: Request forbidden: [PUT http://192.168.0.38/image/v2/images/1de8a905-939d-40c0-a5c5-65893016f5b2/members/6b42ca2487154dabb28bd49b31e5e257], error message: {"message": "Not allowed to update members for image 1de8a905-939d-40c0-a5c5-65893016f5b2.<br /><br />\n\n\n", "code": "403 Forbidden", "title": "Forbidden"}
2021-08-21 18:12:51.412784 | ubuntu-focal |
2021-08-21 18:12:51.412986 | ubuntu-focal |   with openstack_images_image_access_accept_v2.image_access_accept_1,
2021-08-21 18:12:51.413289 | ubuntu-focal |   on terraform_plugin_test.tf line 25, in resource "openstack_images_image_access_accept_v2" "image_access_accept_1":
2021-08-21 18:12:51.413494 | ubuntu-focal |   25: resource "openstack_images_image_access_accept_v2" "image_access_accept_1" {
2021-08-21 18:12:51.413552 | ubuntu-focal |
2021-08-21 18:12:51.413914 | ubuntu-focal |     TestAccImagesImageAccessAcceptV2_basic: resource_openstack_images_image_access_accept_v2_test.go:16: Step 1/2 error: Error running apply: exit status 1
2021-08-21 18:12:51.413958 | ubuntu-focal |
2021-08-21 18:12:51.415040 | ubuntu-focal |         Error: Error setting a member status to the "1de8a905-939d-40c0-a5c5-65893016f5b2" image share for the "6b42ca2487154dabb28bd49b31e5e257" member: Request forbidden: [PUT http://192.168.0.38/image/v2/images/1de8a905-939d-40c0-a5c5-65893016f5b2/members/6b42ca2487154dabb28bd49b31e5e257], error message: {"message": "Not allowed to update members for image 1de8a905-939d-40c0-a5c5-65893016f5b2.<br /><br />\n\n\n", "code": "403 Forbidden", "title": "Forbidden"}
2021-08-21 18:12:51.415089 | ubuntu-focal |
2021-08-21 18:12:51.415280 | ubuntu-focal |           with openstack_images_image_access_accept_v2.image_access_accept_1,
2021-08-21 18:12:51.415576 | ubuntu-focal |           on terraform_plugin_test.tf line 25, in resource "openstack_images_image_access_accept_v2" "image_access_accept_1":
2021-08-21 18:12:51.415813 | ubuntu-focal |           25: resource "openstack_images_image_access_accept_v2" "image_access_accept_1" {
```

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
Issue about images access error https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1283

**Comment by ozerovandrei** [comment]
Admin tests failures:
```
2021-08-25 10:05:27.492961 | ubuntu-focal | 2021/08/25 10:05:27 [DEBUG] OpenStack Response Body: {
2021-08-25 10:05:27.493073 | ubuntu-focal |   "error": {
2021-08-25 10:05:27.493234 | ubuntu-focal |     "code": 409,
2021-08-25 10:05:27.494273 | ubuntu-focal |     "message": "Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is project_1, project id ce
2627cb23e74bf5823d42290030af24.",
2021-08-25 10:05:27.494483 | ubuntu-focal |     "title": "Conflict"
2021-08-25 10:05:27.494584 | ubuntu-focal |   }
2021-08-25 10:05:27.494728 | ubuntu-focal | }
2021-08-25 10:05:28.471957 | ubuntu-focal | 2021/08/25 10:05:28 [WARN] Got error running Terraform: exit status 1
2021-08-25 10:05:28.472117 | ubuntu-focal |
2021-08-25 10:05:28.472836 | ubuntu-focal | Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:05:28.473454 | ubuntu-focal | {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is project_
1, project id ce2627cb23e74bf5823d42290030af24.","title":"Conflict"}}
2021-08-25 10:05:28.473565 | ubuntu-focal |
2021-08-25 10:05:28.473603 | ubuntu-focal |
2021-08-25 10:05:28.473728 | ubuntu-focal |   with openstack_identity_project_v3.project_1,
2021-08-25 10:05:28.474007 | ubuntu-focal |   on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:05:28.474168 | ubuntu-focal |    2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:05:28.474193 | ubuntu-focal |
2021-08-25 10:05:28.474510 | ubuntu-focal |     TestAccComputeQuotasetV2_basic: resource_openstack_compute_quotaset_v2_test.go:21: Step 1/3 error: Error running apply: exit status 1
2021-08-25 10:05:28.474554 | ubuntu-focal |
2021-08-25 10:05:28.474984 | ubuntu-focal |         Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:05:28.475593 | ubuntu-focal |         {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is
project_1, project id ce2627cb23e74bf5823d42290030af24.","title":"Conflict"}}
2021-08-25 10:05:28.475635 | ubuntu-focal |
2021-08-25 10:05:28.475676 | ubuntu-focal |
2021-08-25 10:05:28.475817 | ubuntu-focal |           with openstack_identity_project_v3.project_1,
2021-08-25 10:05:28.476058 | ubuntu-focal |           on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:05:28.476227 | ubuntu-focal |            2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:05:28.476269 | ubuntu-focal |
2021-08-25 10:05:28.649902 | ubuntu-focal | --- FAIL: TestAccComputeQuotasetV2_basic (5.91s)
```
```
2021-08-25 10:07:12.700507 | ubuntu-focal | 2021/08/25 10:07:12 [DEBUG] Retrieved openstack_identity_role_v3: &roles.Role{DomainID:"", ID:"bcf1aea44c6a4b77b7686f28f205f7a0", Links:map[string]interface {}{"self":"http://192.168.0.24/identi
ty/v3/roles/bcf1aea44c6a4b77b7686f28f205f7a0"}, Name:"role_1", Extra:map[string]interface {}{"description":interface {}(nil), "options":map[string]interface {}{}}}
2021-08-25 10:07:13.605021 | ubuntu-focal | 2021/08/25 10:07:13 [WARN] Got error running Terraform: exit status 1
2021-08-25 10:07:13.605139 | ubuntu-focal |
2021-08-25 10:07:13.605577 | ubuntu-focal | Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:07:13.606313 | ubuntu-focal | {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is project_
1, project id a70a940cda0c46fa8cb004f63a41b035.","title":"Conflict"}}
2021-08-25 10:07:13.606388 | ubuntu-focal |
2021-08-25 10:07:13.606418 | ubuntu-focal |
2021-08-25 10:07:13.606558 | ubuntu-focal |   with openstack_identity_project_v3.project_1,
2021-08-25 10:07:13.606842 | ubuntu-focal |   on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:07:13.607024 | ubuntu-focal |    2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:07:13.607051 | ubuntu-focal |
2021-08-25 10:07:13.607439 | ubuntu-focal |     TestAccIdentityV3RoleAssignment_basic: resource_openstack_identity_role_assignment_v3_test.go:20: Step 1/1 error: Error running apply: exit status 1
2021-08-25 10:07:13.607503 | ubuntu-focal |
2021-08-25 10:07:13.608015 | ubuntu-focal |         Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:07:13.608771 | ubuntu-focal |         {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is
project_1, project id a70a940cda0c46fa8cb004f63a41b035.","title":"Conflict"}}
2021-08-25 10:07:13.608859 | ubuntu-focal |
2021-08-25 10:07:13.608908 | ubuntu-focal |
2021-08-25 10:07:13.609066 | ubuntu-focal |           with openstack_identity_project_v3.project_1,
2021-08-25 10:07:13.609334 | ubuntu-focal |           on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:07:13.609522 | ubuntu-focal |            2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:07:13.609569 | ubuntu-focal |
```
```
2021-08-25 10:18:10.884257 | ubuntu-focal | 2021/08/25 10:18:10 [DEBUG] OpenStack Response Body: {
2021-08-25 10:18:10.884347 | ubuntu-focal |   "error": {
2021-08-25 10:18:10.884417 | ubuntu-focal |     "code": 409,
2021-08-25 10:18:10.885021 | ubuntu-focal |     "message": "Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is project_1, project id b1
f477ecfc254e1d8a2fd8aab54c898b.",
2021-08-25 10:18:10.885106 | ubuntu-focal |     "title": "Conflict"
2021-08-25 10:18:10.885141 | ubuntu-focal |   }
2021-08-25 10:18:10.885171 | ubuntu-focal | }
2021-08-25 10:18:11.257214 | ubuntu-focal | 2021/08/25 10:18:11 [WARN] Got error running Terraform: exit status 1
2021-08-25 10:18:11.257516 | ubuntu-focal |
2021-08-25 10:18:11.258359 | ubuntu-focal | Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:18:11.259270 | ubuntu-focal | {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is project_
1, project id b1f477ecfc254e1d8a2fd8aab54c898b.","title":"Conflict"}}
2021-08-25 10:18:11.259360 | ubuntu-focal |
2021-08-25 10:18:11.259431 | ubuntu-focal |
2021-08-25 10:18:11.259617 | ubuntu-focal |   with openstack_identity_project_v3.project_1,
2021-08-25 10:18:11.260023 | ubuntu-focal |   on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:18:11.260244 | ubuntu-focal |    2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:18:11.260312 | ubuntu-focal |
2021-08-25 10:18:11.260802 | ubuntu-focal |     TestAccNetworkingQuotaV2_basic: resource_openstack_networking_quota_v2_test.go:14: Step 1/3 error: Error running apply: exit status 1
2021-08-25 10:18:11.260903 | ubuntu-focal |
2021-08-25 10:18:11.261311 | ubuntu-focal |         Error: Error creating openstack_identity_project_v3: Expected HTTP response code [] when accessing [POST http://192.168.0.24/identity/v3/projects], but got 409 instead
2021-08-25 10:18:11.261812 | ubuntu-focal |         {"error":{"code":409,"message":"Conflict occurred attempting to store project - it is not permitted to have two projects with either the same name or same id in the same domain: name is
project_1, project id b1f477ecfc254e1d8a2fd8aab54c898b.","title":"Conflict"}}
2021-08-25 10:18:11.261894 | ubuntu-focal |
2021-08-25 10:18:11.261960 | ubuntu-focal |
2021-08-25 10:18:11.262060 | ubuntu-focal |           with openstack_identity_project_v3.project_1,
2021-08-25 10:18:11.262247 | ubuntu-focal |           on terraform_plugin_test.tf line 2, in resource "openstack_identity_project_v3" "project_1":
2021-08-25 10:18:11.262367 | ubuntu-focal |            2: resource "openstack_identity_project_v3" "project_1" {
2021-08-25 10:18:11.262397 | ubuntu-focal |
2021-08-25 10:18:11.440256 | ubuntu-focal | --- FAIL: TestAccNetworkingQuotaV2_basic (4.82s)
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Pull request merged**
