### PR TITLE
blockstorage_quotaset_v2/3: Convert volume_type_quota to int 

### PR DESCRIPTION
**Pull request by nikParasyr**
Explicit convert volume_type_quota values to int.
Update tests to add volume type creation and volume_type_quota
updates.

For: #1193
Requires: #1204

### CODE REVIEW

**Comment by nikParasyr** [comment]
recheck

**Comment by nikParasyr** [comment]
@ozerovandrei This can be merged as well from my side, it requires #1204. I've tested this on a latest devstack as well. Outputs of the tests are [here](https://gist.github.com/nikParasyr/c2c582ab4f5bd750d282c4bc44d701c7) and [here](https://gist.github.com/nikParasyr/25f64be709083ab6366862e59f516b02)

**Comment by nikParasyr** [comment]
recheck

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
