### PR TITLE
Add containerinfra nodegroup support

### PR DESCRIPTION
**Pull request by MrFreezeex**
This PR adds resource and data source support for OpenStack Magnum node groups.

I added support for zero node_count cluster and nodegroup.
And I also fixed the merge_labels behavior and added it to the nodegroup resource as well

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
@MrFreezeex ping, is there any progress on this? Thanks

**Comment by MrFreezeex** [comment]
> @MrFreezeex ping, is there any progress on this? Thanks

Well AFAIK it works just fine, it won't probably be merged anytime soon because of the various pinned issue, including: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1366

**Comment by MrFreezeex** [comment]
I also fixed the merge_labels behavior of the cluster resource/added merge_labels support for nodegroup since this https://github.com/gophercloud/gophercloud/pull/2377 was merged and released in 0.25.0.

**Review by ozerovandrei — APPROVED** [review]
LGTM.
I can merge this without running acceptance tests in CI if it's ready and has been manually tested.

**Comment by MrFreezeex** [comment]
@ozerovandrei I tested the acceptances tests on our OpenStack cluster and it now works. I had to make a couple of changes including changing the way we get the magnum image as the one that we used was deprecated since a long time and the link was not available. I suspect that the acceptance was not working on cluster also as I fixed a bug there, now everything should be much better handled!

**Comment by ozerovandrei** [comment]
Thank you @MrFreezeex

**Pull request merged**
