### PR TITLE
[containerinfra_cluster_v1] add kubeconfig to data source

### LINKED ISSUE #1442: data source for openstack_containerinfra_cluster_v1
Can someone add more attributes to this resource 

https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/containerinfra_cluster_v1

kubeconfig - The Kubernetes cluster's credentials

 raw_config - The raw kubeconfig file
 host - The cluster's API server URL
 cluster_ca_certificate - The cluster's CA certificate
 client_key - The client's RSA key
 client_certificate - The client's certificate
 
 
 it would be easy to deploy containers on kubernetes cluster  via terraform

### PR DESCRIPTION
**Pull request by MichaelBitard**
Hello,

We needed the kubeconfig attribute in order to parameter our kubernetes provider, so we implemented it.

I hope we did not miss anything, we are using it right now and it  :copyright: works on my machine :copyright: 

fix #1442

### CODE REVIEW

**Comment by MichaelBitard** [comment]
This is basically a small copy/pasta from resource_openstack_containerinfra_cluster_v1.go, I think it should be straigthforward to review ;)

**Comment by nikParasyr** [comment]
@MichaelBitard thanks you for the PR. Ill have time next week to review it

**Review by nikParasyr — APPROVED** [review]
LGTM

**Comment by Eldrile** [comment]
@nikParasyr Thanks a lot for the merge ! I work with Michael on the project needing this option.
Do you have an idea when a new release will take place?

**Comment by Eldrile** [comment]
Thanks a lot !

**Pull request merged**
