### PR TITLE
Add region option for openstack_compute_aggregate_v2

### PR DESCRIPTION
**Pull request by fitbeard**
Add region option. Will be useful in a setup with multiple regions.

### CODE REVIEW

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
recheck

**Comment by fitbeard** [comment]
@ozerovandrei can you review this small change please.

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
