### PR TITLE
Correctly handle missing flavors in openstack_compute_instance_v2

### PR DESCRIPTION
**Pull request by rnurgaliyev**
This PR fixes issue #1361

### CODE REVIEW

**Comment by rnurgaliyev-s11** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by rnurgaliyev-s11** [comment]
Not hundred 100% sure why tests are failing, zuul logs are not very informative at first glance.

**Comment by rnurgaliyev-s11** [comment]
Not hundred 100% sure why tests are failing, zuul logs are not very informative at first glance.

**Comment by rnurgaliyev-s11** [comment]
recheck

**Comment by rnurgaliyev-s11** [comment]
recheck

**Comment by rnurgaliyev** [comment]
recheck

**Comment by ozerovandrei** [comment]
https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1366

**Review by nikParasyr — APPROVED** [review]

**Pull request merged**
