### PR TITLE
Add ci configuration for openlab zuul

### PR DESCRIPTION
**Pull request by nikParasyr**
For #1253 

Copy the zuul job configurations from openlab to allow
easier/faster updates.

### CODE REVIEW

**Comment by nikParasyr** [comment]
recheck-bsv2

**Comment by nikParasyr** [comment]
recheck bsv2

**Comment by nikParasyr** [comment]
recheck bsv2-admin

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
recheck lbaas

**Comment by nikParasyr** [comment]
@ozerovandrei Couple of things:
- I copied the playbooks and added the job definitions based on what was on openlab. I had to change the name of the jobs (appended a `-foo`) because they were duplicate. If we go forward with this I can make a PR to openlab to remove the definitions from there and then i can remove `-foo` from here.
- Added 2 new jobs for BlockStorageV2 tests and updated all the tests accordingly. The jobs are based a bit on https://review.opendev.org/c/openstack/tempest/+/792025/.

Currently i'm facing 2 problems that I'm not sure what the reason is.
- The jobs do run and finish on openlab (i can see/find the logs etc ) but the PR is not updated with the result. Not sure why. Wonder if it is a permissions thingy or something like that that i dont have permissions to check.
- The 2 new jobs that i have added do not get triggered by comments. Not sure why. There was a similar issue when i added the admin job and a restart of zuul was required.

**Comment by nikParasyr** [comment]
recheck bsv2

**Review by ozerovandrei — APPROVED** [review]
Thank you @nikParasyr !

**Pull request merged**
