### PR TITLE
DNM test CI

### PR DESCRIPTION
**Pull request by ozerovandrei**

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
recheck trove

**Comment by ozerovandrei** [comment]
recheck fwaas

**Comment by ozerovandrei** [comment]
recheck designate

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
LbaaS test is failing with:
```
2020-09-17 10:31:11.411 | ++ /opt/stack/new/octavia/devstack/plugin.sh:build_octavia_worker_image:126 :   /opt/stack/new/octavia/diskimage-create/diskimage-create.sh -l /var/log/dib-build/amphora-x64-haproxy.qcow2.log -x -o /opt/stack/new/octavia/diskimage-create/amphora-x64-haproxy.qcow2
2020-09-17 10:31:11.762 | /opt/stack/new/octavia/diskimage-create/diskimage-create.sh: line 500: disk-image-create: command not found
```

**Comment by ozerovandrei** [comment]
Trove test is failing with:
```
2020-09-17 09:01:12.065156 | ubuntu-bionic | setting PATH=/opt/stack/new/trove/.tox/trovestack/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
2020-09-17 09:01:12.081143 | ubuntu-bionic | [751] /opt/stack/new/trove/integration/scripts$ /opt/stack/new/trove/integration/scripts/trovestack kick-start mysql
2020-09-17 09:01:12.443899 | ubuntu-bionic | 'kick-start' not a valid command
2020-09-17 09:01:12.444855 | ubuntu-bionic | ERROR: InvocationError for command /opt/stack/new/trove/integration/scripts/trovestack kick-start mysql (exited with code 1)
```

**Comment by ozerovandrei** [comment]
FWaas test is failing with:
```
2020-09-17 08:47:55.982546 | ubuntu-bionic | 2020/09/17 08:47:55 [DEBUG] OpenStack Endpoint for network: http://192.168.0.22:9696/v2.0/
2020-09-17 08:47:55.982810 | ubuntu-bionic | 2020/09/17 08:47:55 [DEBUG] openstack_fw_policy_v1 create options: openstack.PolicyCreateOpts{CreateOpts:policies.CreateOpts{TenantID:"", ProjectID:"", Name:"policy_1", Description:"", Shared:(*bool)(nil), Audited:(*bool)(0xc0006cb2e0), Rules:[]string{}}, ValueSpecs:map[string]string{}}
2020-09-17 08:47:56.060793 | ubuntu-bionic | 2020/09/17 08:47:56 [DEBUG] openstack_fw_policy_v1.policy_1: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating openstack_fw_policy_v1: Resource not found
```

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
recheck trove

**Comment by wangxiyuan** [comment]
recheck trove

**Comment by pbasov** [comment]
recheck-designate

**Comment by pbasov** [comment]
recheck designate

**Pull request closed without merging**
