### PR TITLE
add system scope auth support

### PR DESCRIPTION
**Pull request by askarsabyrov**
Fixes: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1516
Did `go get github.com/gophercloud/utils`

### CODE REVIEW

**Comment by kayrus** [comment]
@askarsabyrov Thanks for the PR. Can you introduce the system scope option along with the dependency update? I don't see a reason to split this into multiple PRs.

**Comment by kayrus** [comment]
@askarsabyrov we're planning a new release. How much time do you need to finish this feature?

**Comment by askarsabyrov** [comment]
> Could you please submit a new PR in gophercloud/utils adding the system scope support into the terraform auth code?
I already made PR to gophercloud/utils https://github.com/gophercloud/utils/pull/183. 
Now I can't use authOpts field in Config struct. If that PR to gophercloud/utils gets merged, I will define AuthOptions in provider. I have no idea why authOpts field were meant to be private in Config struct, hope my PR will be merged. 

> @askarsabyrov we're planning a new release. How much time do you need to finish this feature?
Suppose, better pass this release, I am not sure how much time it will take.

**Comment by askarsabyrov** [comment]
@kayrus have you take a look? builded and tested, works as expected. 
Debug log when system_scope=true:
```
TF_LOG=DEBUG OS_DEBUG=1 terraform plan
2023-03-24T13:18:05.011+0600 [INFO]  provider.terraform-provider-openstack_v1.51.0: 2023/03/24 13:18:05 [DEBUG] OpenStack Request Body: {
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "domain": {
            "name": "Default"
          },
          "name": "askar.sabyrov",
          "password": "***"
        }
      }
    },
    "scope": {
      "system": {
        "all": true
      }
    }
  }
}
```

**Review by nikParasyr — CHANGES_REQUESTED** [review]
@askarsabyrov Thanks for this. Could you plz update the docs [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/website/docs/index.html.markdown) with the new option?

**Comment by askarsabyrov** [comment]
@nikParasyr thanks for review! added description to `system_scope` arguments to docs

**Review by nikParasyr — APPROVED** [review]

**Review by kayrus — APPROVED** [review]
I don't know exactly what I don't like, maybe it's how it's implemented in gophercloud/utils, but since the change is already there, okay :)

**Pull request merged**
