### PR TITLE
Bump Gophercloud

### PR DESCRIPTION
**Pull request by pierreprinetti**
Remove a dependency on a deprecated package: utils now uses "imageservice"
instead of "compute" to resolve image IDs.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
This issue is actually less anodyne than it looks. Because of how Minimal version selection works, the backwards-incompatible change introduced in utils is breaking `go mod` in dependant packages.

This patch changes `terraform-provider-openstack` so that it does not depend any more on a removed `utils` function.

**Review by mandre — COMMENTED** [review]
Thanks :+1:

**Review by mandre — APPROVED** [review]

**Review by Fedosin — APPROVED** [review]
LGTM

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
